
SET SERVEROUTPUT ON
SET DEFINE OFF

PROMPT ====== DROPS SEGUROS (TABLAS HIJAS -> PADRES) ======
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_FACTURA_ONLINE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_TICKET CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_PEDIDO_PROV CASCADE CONSTRAINTS';   EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ENVIO_ONLINE CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEVOLUCION_TICKET CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIRECCION_ENVIO CASCADE CONSTRAINTS';       EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DATOS_FACTURACION CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECEPCION_PEDIDO CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALBARAN_AUTONOMO CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PEDIDO_PROVEEDOR CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FACTURA_ONLINE CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TICKET_CAJA CASCADE CONSTRAINTS';           EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FACTURA_COMPRA CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLIENTE_PARTICULAR CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO_TIENDA CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROVEEDOR_AUTONOMO CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROVEEDOR_SOCIEDAD CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARTICULO CASCADE CONSTRAINTS';              EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ARTICULO';                           EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

PROMPT ====== CREACIÓN DE TABLAS (PADRES) ======
CREATE TABLE ARTICULO (
    ID_ARTICULO     NUMBER,
    NOMBRE          VARCHAR2(120),
    DETALLE         VARCHAR2(255),
    COD_REFERENCIA  VARCHAR2(24),
    CANTIDAD_DISP   NUMBER,
    PRECIO_UNIT     NUMBER(8,2),
    CONSTRAINT PK_ARTICULO PRIMARY KEY (ID_ARTICULO),
    CONSTRAINT CK_ARTICULO_NOMBRE_NN CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT CK_ARTICULO_REF_NN   CHECK (COD_REFERENCIA IS NOT NULL),
    CONSTRAINT CK_ARTICULO_CANT_OK  CHECK (CANTIDAD_DISP IS NOT NULL AND CANTIDAD_DISP >= 0),
    CONSTRAINT CK_ARTICULO_PREC_OK  CHECK (PRECIO_UNIT IS NOT NULL AND PRECIO_UNIT > 0),
    CONSTRAINT UQ_ARTICULO_REF      UNIQUE (COD_REFERENCIA)
);

CREATE TABLE PROVEEDOR_SOCIEDAD (
    ID_PROV_SOC     NUMBER,
    CIF             VARCHAR2(9),
    CP              NUMBER(5),
    SITIO_WEB       VARCHAR2(120),
    RAZON_SOCIAL    VARCHAR2(120),
    TELEFONO        NUMBER(9),
    DIRECCION       VARCHAR2(160),
    PERSONA_CONTACTO VARCHAR2(60),
    LOCALIDAD       VARCHAR2(60),
    CONSTRAINT PK_PROV_SOC PRIMARY KEY (ID_PROV_SOC),
    CONSTRAINT UQ_PROV_SOC_CIF UNIQUE (CIF),
    CONSTRAINT CK_PROV_SOC_REQ CHECK (
        CIF IS NOT NULL AND CP IS NOT NULL AND RAZON_SOCIAL IS NOT NULL AND
        TELEFONO IS NOT NULL AND DIRECCION IS NOT NULL AND LOCALIDAD IS NOT NULL
    ),
    CONSTRAINT CK_PROV_SOC_TEL CHECK (TELEFONO BETWEEN 600000000 AND 999999999)
);

CREATE TABLE PROVEEDOR_AUTONOMO (
    ID_PROV_AUT     NUMBER,
    MARCA_COMERCIAL VARCHAR2(120),
    DNI             VARCHAR2(9),
    TELEFONO        NUMBER(9),
    LOCALIDAD       VARCHAR2(60),
    DIRECCION       VARCHAR2(160),
    NOMBRE          VARCHAR2(60),
    APELLIDOS       VARCHAR2(120),
    CONSTRAINT PK_PROV_AUT PRIMARY KEY (ID_PROV_AUT),
    CONSTRAINT UQ_PROV_AUT_DNI UNIQUE (DNI),
    CONSTRAINT CK_PROV_AUT_REQ CHECK (
        DNI IS NOT NULL AND TELEFONO IS NOT NULL AND LOCALIDAD IS NOT NULL AND
        DIRECCION IS NOT NULL AND NOMBRE IS NOT NULL AND APELLIDOS IS NOT NULL
    ),
    CONSTRAINT CK_PROV_AUT_TEL CHECK (TELEFONO BETWEEN 600000000 AND 999999999)
);

CREATE TABLE USUARIO_TIENDA (
    ID_USUARIO  NUMBER,
    ALIAS       VARCHAR2(60),
    TELEFONO    NUMBER(9),
    HASH_CLAVE  VARCHAR2(255),
    CORREO      VARCHAR2(120),
    NOMBRE      VARCHAR2(60),
    APELLIDO    VARCHAR2(120),
    CONSTRAINT PK_USUARIO_TIENDA PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIO_ALIAS  UNIQUE (ALIAS),
    CONSTRAINT UQ_USUARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_USUARIO_REQ CHECK (
        ALIAS IS NOT NULL AND TELEFONO IS NOT NULL AND HASH_CLAVE IS NOT NULL AND
        CORREO IS NOT NULL AND NOMBRE IS NOT NULL AND APELLIDO IS NOT NULL
    ),
    CONSTRAINT CK_USUARIO_TEL CHECK (TELEFONO BETWEEN 600000000 AND 999999999)
);

CREATE TABLE CLIENTE_PARTICULAR (
    ID_CLIENTE NUMBER,
    CONSTRAINT PK_CLIENTE_PARTICULAR PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE FACTURA_COMPRA (
    ID_FACT_COMP NUMBER,
    FECHA        DATE DEFAULT SYSDATE,
    CONSTRAINT PK_FACTURA_COMPRA PRIMARY KEY (ID_FACT_COMP),
    CONSTRAINT CK_FACT_COMP_FECHA_NN CHECK (FECHA IS NOT NULL)
);

PROMPT ====== CREACIÓN DE TABLAS (DEPENDIENTES) ======
CREATE TABLE PEDIDO_PROVEEDOR (
    ID_PED_PROV NUMBER,
    FECHA       DATE DEFAULT SYSDATE,
    ID_PROV_SOC NUMBER,
    CONSTRAINT PK_PEDIDO_PROVEEDOR PRIMARY KEY (ID_PED_PROV),
    CONSTRAINT CK_PED_PROV_REQ CHECK (FECHA IS NOT NULL AND ID_PROV_SOC IS NOT NULL),
    CONSTRAINT FK_PED_PROV_SOC FOREIGN KEY (ID_PROV_SOC) REFERENCES PROVEEDOR_SOCIEDAD(ID_PROV_SOC)
);

CREATE TABLE RECEPCION_PEDIDO (
    ID_RECEPCION NUMBER,
    ACEPTADO     VARCHAR2(2),
    FECHA        DATE DEFAULT SYSDATE,
    ID_PED_PROV  NUMBER,
    ID_FACT_COMP NUMBER,
    CONSTRAINT PK_RECEPCION_PEDIDO PRIMARY KEY (ID_RECEPCION),
    CONSTRAINT CK_RECEP_REQ CHECK (ACEPTADO IS NOT NULL AND FECHA IS NOT NULL AND ID_PED_PROV IS NOT NULL AND ID_FACT_COMP IS NOT NULL),
    CONSTRAINT CK_RECEP_ACEPTADO CHECK (ACEPTADO IN ('SI','NO')),
    CONSTRAINT FK_RECEP_PED  FOREIGN KEY (ID_PED_PROV)  REFERENCES PEDIDO_PROVEEDOR(ID_PED_PROV),
    CONSTRAINT FK_RECEP_FACT FOREIGN KEY (ID_FACT_COMP) REFERENCES FACTURA_COMPRA(ID_FACT_COMP)
);

CREATE TABLE ALBARAN_AUTONOMO (
    ID_ALBARAN  NUMBER,
    FECHA       DATE DEFAULT SYSDATE,
    ID_PROV_AUT NUMBER,
    CONSTRAINT PK_ALBARAN_AUTONOMO PRIMARY KEY (ID_ALBARAN),
    CONSTRAINT CK_ALBARAN_REQ CHECK (FECHA IS NOT NULL AND ID_PROV_AUT IS NOT NULL),
    CONSTRAINT FK_ALB_AUT FOREIGN KEY (ID_PROV_AUT) REFERENCES PROVEEDOR_AUTONOMO(ID_PROV_AUT)
);

CREATE TABLE TICKET_CAJA (
    ID_TICKET     NUMBER,
    FECHA         DATE DEFAULT SYSDATE,
    FORMA_PAGO    VARCHAR2(20),
    NUM_OPERACION VARCHAR2(60),
    ID_CLIENTE    NUMBER,
    CONSTRAINT PK_TICKET_CAJA PRIMARY KEY (ID_TICKET),
    CONSTRAINT CK_TICKET_REQ CHECK (FECHA IS NOT NULL AND FORMA_PAGO IS NOT NULL AND ID_CLIENTE IS NOT NULL),
    CONSTRAINT CK_TICKET_PAGO CHECK (FORMA_PAGO IN ('EFECTIVO','TARJETA','BIZUM','OTRO')),
    CONSTRAINT FK_TICKET_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_PARTICULAR(ID_CLIENTE)
);

CREATE TABLE DEVOLUCION_TICKET (
    ID_DEV        NUMBER,
    FECHA         DATE DEFAULT SYSDATE,
    MOTIVO        VARCHAR2(255),
    TIPO_REEMBOLSO VARCHAR2(20),
    UNIDADES      NUMBER,
    ID_TICKET     NUMBER,
    CONSTRAINT PK_DEVOLUCION_TICKET PRIMARY KEY (ID_DEV),
    CONSTRAINT CK_DEV_TICKET_REQ CHECK (FECHA IS NOT NULL AND MOTIVO IS NOT NULL AND TIPO_REEMBOLSO IS NOT NULL AND UNIDADES IS NOT NULL AND ID_TICKET IS NOT NULL),
    CONSTRAINT CK_DEV_TIPO CHECK (TIPO_REEMBOLSO IN ('EFECTIVO','TARJETA','BIZUM','OTRO')),
    CONSTRAINT CK_DEV_UNIDADES CHECK (UNIDADES > 0),
    CONSTRAINT FK_DEV_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKET_CAJA(ID_TICKET)
);

CREATE TABLE DIRECCION_ENVIO (
    ID_DIRECCION NUMBER,
    CP           NUMBER(5),
    CALLE        VARCHAR2(160),
    PROVINCIA    VARCHAR2(60),
    LOCALIDAD    VARCHAR2(60),
    PRINCIPAL    VARCHAR2(2),
    ID_USUARIO   NUMBER,
    CONSTRAINT PK_DIRECCION_ENVIO PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT CK_DIR_ENV_REQ CHECK (CP IS NOT NULL AND CALLE IS NOT NULL AND PROVINCIA IS NOT NULL AND LOCALIDAD IS NOT NULL AND PRINCIPAL IS NOT NULL AND ID_USUARIO IS NOT NULL),
    CONSTRAINT CK_DIR_ENV_PRINC CHECK (PRINCIPAL IN ('SI','NO')),
    CONSTRAINT FK_DIR_ENV_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO_TIENDA(ID_USUARIO)
);

CREATE TABLE DATOS_FACTURACION (
    ID_DATO_FACT NUMBER,
    EMPRESA      VARCHAR2(120),
    CIF          VARCHAR2(9),
    DIRECCION    VARCHAR2(160),
    ID_USUARIO   NUMBER,
    CONSTRAINT PK_DATOS_FACTURACION PRIMARY KEY (ID_DATO_FACT),
    CONSTRAINT CK_DATO_FACT_REQ CHECK (EMPRESA IS NOT NULL AND CIF IS NOT NULL AND DIRECCION IS NOT NULL AND ID_USUARIO IS NOT NULL),
    CONSTRAINT FK_DATO_FACT_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO_TIENDA(ID_USUARIO)
);

CREATE TABLE FACTURA_ONLINE (
    ID_FACT_ONLINE NUMBER,
    FECHA          DATE DEFAULT SYSDATE,
    METODO_PAGO    VARCHAR2(20),
    COSTE_ENVIO    NUMBER(6,2),
    ID_USUARIO     NUMBER,
    CONSTRAINT PK_FACTURA_ONLINE PRIMARY KEY (ID_FACT_ONLINE),
    CONSTRAINT CK_FACT_ON_REQ CHECK (FECHA IS NOT NULL AND METODO_PAGO IS NOT NULL AND COSTE_ENVIO IS NOT NULL AND ID_USUARIO IS NOT NULL),
    CONSTRAINT CK_FACT_ON_PAGO CHECK (METODO_PAGO IN ('TARJETA','PAYPAL','BIZUM','TRANSFERENCIA')),
    CONSTRAINT CK_FACT_ON_ENVIO CHECK (COSTE_ENVIO >= 0),
    CONSTRAINT FK_FACT_ON_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO_TIENDA(ID_USUARIO)
);

CREATE TABLE ENVIO_ONLINE (
    ID_ENVIO        NUMBER,
    FECHA           DATE DEFAULT SYSDATE,
    COD_SEGUIMIENTO VARCHAR2(60),
    TRANSPORTISTA   VARCHAR2(120),
    ID_FACT_ONLINE  NUMBER,
    CONSTRAINT PK_ENVIO_ONLINE PRIMARY KEY (ID_ENVIO),
    CONSTRAINT CK_ENV_ON_REQ CHECK (FECHA IS NOT NULL AND COD_SEGUIMIENTO IS NOT NULL AND TRANSPORTISTA IS NOT NULL AND ID_FACT_ONLINE IS NOT NULL),
    CONSTRAINT FK_ENV_ON_FACT FOREIGN KEY (ID_FACT_ONLINE) REFERENCES FACTURA_ONLINE(ID_FACT_ONLINE)
);

CREATE TABLE DETALLE_FACTURA_ONLINE (
    ID_DETALLE     NUMBER,
    CANTIDAD       NUMBER,
    IMPORTE        NUMBER(8,2),
    ID_FACT_ONLINE NUMBER,
    ID_ARTICULO    NUMBER,
    CONSTRAINT PK_DETALLE_FACTURA_ONLINE PRIMARY KEY (ID_DETALLE),
    CONSTRAINT CK_DFO_REQ     CHECK (CANTIDAD IS NOT NULL AND IMPORTE IS NOT NULL AND ID_FACT_ONLINE IS NOT NULL AND ID_ARTICULO IS NOT NULL),
    CONSTRAINT CK_DFO_CANT    CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DFO_IMPORTE CHECK (IMPORTE > 0),
    CONSTRAINT FK_DFO_FACT FOREIGN KEY (ID_FACT_ONLINE) REFERENCES FACTURA_ONLINE(ID_FACT_ONLINE),
    CONSTRAINT FK_DFO_ART  FOREIGN KEY (ID_ARTICULO)    REFERENCES ARTICULO(ID_ARTICULO)
);

CREATE TABLE DETALLE_TICKET (
    ID_DET_TICKET NUMBER,
    IMPORTE       NUMBER(8,2),
    CANTIDAD      NUMBER,
    ID_TICKET     NUMBER,
    ID_ARTICULO   NUMBER,
    CONSTRAINT PK_DETALLE_TICKET PRIMARY KEY (ID_DET_TICKET),
    CONSTRAINT CK_DT_REQ      CHECK (IMPORTE IS NOT NULL AND CANTIDAD IS NOT NULL AND ID_TICKET IS NOT NULL AND ID_ARTICULO IS NOT NULL),
    CONSTRAINT CK_DT_IMPORTE  CHECK (IMPORTE > 0),
    CONSTRAINT CK_DT_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT FK_DT_TICKET FOREIGN KEY (ID_TICKET)  REFERENCES TICKET_CAJA(ID_TICKET),
    CONSTRAINT FK_DT_ART    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO)
);

CREATE TABLE DETALLE_PEDIDO_PROV (
    ID_DET_PED  NUMBER,
    IMPORTE     NUMBER(8,2),
    CANTIDAD    NUMBER,
    ID_ARTICULO NUMBER,
    ID_PED_PROV NUMBER,
    CONSTRAINT PK_DETALLE_PEDIDO_PROV PRIMARY KEY (ID_DET_PED),
    CONSTRAINT CK_DPP_REQ     CHECK (IMPORTE IS NOT NULL AND CANTIDAD IS NOT NULL AND ID_ARTICULO IS NOT NULL AND ID_PED_PROV IS NOT NULL),
    CONSTRAINT CK_DPP_IMPORTE CHECK (IMPORTE > 0),
    CONSTRAINT CK_DPP_CANT    CHECK (CANTIDAD > 0),
    CONSTRAINT FK_DPP_ART FOREIGN KEY (ID_ARTICULO)  REFERENCES ARTICULO(ID_ARTICULO),
    CONSTRAINT FK_DPP_PED FOREIGN KEY (ID_PED_PROV)  REFERENCES PEDIDO_PROVEEDOR(ID_PED_PROV)
);

PROMPT ====== SECUENCIA (ARTICULO) ======
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_ARTICULO START WITH 2000 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

PROMPT ====== ÍNDICES PARA FKs ======
CREATE INDEX IX_DET_TICKET_TICKET     ON DETALLE_TICKET (ID_TICKET);
CREATE INDEX IX_DET_TICKET_ARTICULO   ON DETALLE_TICKET (ID_ARTICULO);
CREATE INDEX IX_DFO_FACT              ON DETALLE_FACTURA_ONLINE (ID_FACT_ONLINE);
CREATE INDEX IX_DFO_ART               ON DETALLE_FACTURA_ONLINE (ID_ARTICULO);
CREATE INDEX IX_ENVIO_FACT            ON ENVIO_ONLINE (ID_FACT_ONLINE);
CREATE INDEX IX_DET_PED_ART           ON DETALLE_PEDIDO_PROV (ID_ARTICULO);
CREATE INDEX IX_DET_PED_PED           ON DETALLE_PEDIDO_PROV (ID_PED_PROV);
CREATE INDEX IX_RECEP_PED             ON RECEPCION_PEDIDO (ID_PED_PROV);
CREATE INDEX IX_RECEP_FACT            ON RECEPCION_PEDIDO (ID_FACT_COMP);
CREATE INDEX IX_DIR_ENV_USUARIO       ON DIRECCION_ENVIO (ID_USUARIO);
CREATE INDEX IX_DATOS_FACT_USUARIO    ON DATOS_FACTURACION (ID_USUARIO);
CREATE INDEX IX_TICKET_CLIENTE        ON TICKET_CAJA (ID_CLIENTE);
CREATE INDEX IX_ALBARAN_PROV_AUT      ON ALBARAN_AUTONOMO (ID_PROV_AUT);
CREATE INDEX IX_PEDIDO_PROV_SOC       ON PEDIDO_PROVEEDOR (ID_PROV_SOC);

PROMPT ====== DATOS DE EJEMPLO ======
INSERT INTO ARTICULO VALUES (1001, 'HP Pavilion 14', 'Portátil i7, 16GB RAM, 512GB SSD', 'HP-P14-I7', 16, 799.00);
INSERT INTO ARTICULO VALUES (1002, 'Logitech M650', 'Ratón inalámbrico silencioso', 'LGT-M650', 48, 39.99);
INSERT INTO ARTICULO VALUES (1003, 'Akko 3068B', 'Teclado mecánico 65% inalámbrico', 'AKK-3068B', 25, 109.90);
INSERT INTO ARTICULO VALUES (1004, 'BenQ GW2780', 'Monitor 27"" FullHD con eye-care', 'BNQ-GW2780', 20, 169.00);
INSERT INTO ARTICULO VALUES (1005, 'Logitech C920s', 'Webcam 1080p con tapa de privacidad', 'LGT-C920S', 35, 74.95);
INSERT INTO ARTICULO VALUES (1006, 'Anker Soundcore Q45', 'Auriculares ANC con BT 5.3', 'ANK-Q45', 22, 139.99);
INSERT INTO ARTICULO VALUES (1007, 'Toshiba Canvio 2TB', 'Disco duro externo 2TB', 'TOS-CAN2TB', 60, 69.90);
INSERT INTO ARTICULO VALUES (1008, 'ASUS RT-AX58U', 'Router WiFi 6 AX3000', 'ASU-AX58U', 18, 149.99);
INSERT INTO ARTICULO VALUES (1009, 'UGREEN USB-C 3m', 'Cable USB-C 100W de 3 m', 'UGR-USBC-3M', 110, 16.99);
INSERT INTO ARTICULO VALUES (1010, 'Satechi USB-C Hub 9en1', 'Hub con HDMI y PD', 'STC-9IN1', 40, 79.99);

INSERT INTO PROVEEDOR_SOCIEDAD VALUES (2001, 'A9080706F', 28007, 'https://digitop.es', 'Digitop Solutions S.A.', 915334455, 'C/ O''Donnell 32', 'Raúl Cebrián', 'Madrid');
INSERT INTO PROVEEDOR_SOCIEDAD VALUES (2002, 'B1122334G', 50010, 'https://zgzbits.es', 'ZGZ Bits S.L.', 976445566, 'Av. Tenor Fleta 45', 'Paula Aliaga', 'Zaragoza');
INSERT INTO PROVEEDOR_SOCIEDAD VALUES (2003, 'C2211334H',  8012, 'https://barna-digital.com', 'Barna Digital S.A.', 934778899, 'C/ Diputació 240', 'Núria Font', 'Barcelona');
INSERT INTO PROVEEDOR_SOCIEDAD VALUES (2004, 'D3344556J', 41004, 'https://sevillacode.es', 'Sevilla Code S.L.', 954667788, 'C/ Imagen 6', 'Hugo Márquez', 'Sevilla');
INSERT INTO PROVEEDOR_SOCIEDAD VALUES (2005, 'E5566778K', 46001, 'https://valbyte.io', 'Valbyte S.A.', 963556677, 'C/ Poeta Querol 9', 'Carla Soriano', 'Valencia');

INSERT INTO PROVEEDOR_AUTONOMO VALUES (3001, 'Firma Norte Bits', '12340987Z', 677889900, 'Bilbao', 'C/ Ercilla 18', 'Aritz', 'García Eguíluz');
INSERT INTO PROVEEDOR_AUTONOMO VALUES (3002, 'Estudio Costa',   '78901234Y', 678990011, 'A Coruña', 'Av. de la Marina 7', 'Uxía', 'Toledo Pájaro');
INSERT INTO PROVEEDOR_AUTONOMO VALUES (3003, 'Apps Centro',     '56789012X', 679001122, 'Valladolid', 'Pº Zorrilla 92', 'Mateo', 'López Navas');
INSERT INTO PROVEEDOR_AUTONOMO VALUES (3004, NULL,              '90123456W', 680112233, 'Alicante', 'Av. Óscar Esplá 15', 'Vera', 'Sanz Maroto');
INSERT INTO PROVEEDOR_AUTONOMO VALUES (3005, 'Diseño Oeste',    '34567890V', 681223344, 'Cáceres', 'C/ Pintores 20', 'Guille', 'Pérez Valiente');

INSERT INTO USUARIO_TIENDA VALUES (4001, 'sergio_av', 677112233, 'h1', 'sergio.avila@tienda.com', 'Sergio', 'Ávila Mora');
INSERT INTO USUARIO_TIENDA VALUES (4002, 'miriam',    678223344, 'h2', 'miriam.garcia@tienda.com', 'Míriam', 'García Cruz');
INSERT INTO USUARIO_TIENDA VALUES (4003, 'raulm',     679334455, 'h3', 'raul.martin@tienda.com', 'Raúl', 'Martín Buira');
INSERT INTO USUARIO_TIENDA VALUES (4004, 'paula_o',   680445566, 'h4', 'paula.ortega@tienda.com', 'Paula', 'Ortega Soro');
INSERT INTO USUARIO_TIENDA VALUES (4005, 'diego.s',   681556677, 'h5', 'diego.soto@tienda.com', 'Diego', 'Soto Vidal');
INSERT INTO USUARIO_TIENDA VALUES (4006, 'lidia',     682667788, 'h6', 'lidia.rodriguez@tienda.com', 'Lidia', 'Rodríguez Vega');
INSERT INTO USUARIO_TIENDA VALUES (4007, 'jaime_t',   683778899, 'h7', 'jaime.trigo@tienda.com', 'Jaime', 'Trigo Pascual');

INSERT INTO CLIENTE_PARTICULAR VALUES (5001);
INSERT INTO CLIENTE_PARTICULAR VALUES (5002);
INSERT INTO CLIENTE_PARTICULAR VALUES (5003);
INSERT INTO CLIENTE_PARTICULAR VALUES (5004);
INSERT INTO CLIENTE_PARTICULAR VALUES (5005);

INSERT INTO FACTURA_COMPRA VALUES (6001, DATE '2025-01-18');
INSERT INTO FACTURA_COMPRA VALUES (6002, DATE '2025-02-14');
INSERT INTO FACTURA_COMPRA VALUES (6003, DATE '2025-03-19');
INSERT INTO FACTURA_COMPRA VALUES (6004, DATE '2025-04-28');
INSERT INTO FACTURA_COMPRA VALUES (6005, DATE '2025-05-24');

INSERT INTO PEDIDO_PROVEEDOR VALUES (7001, DATE '2025-01-10', 2001);
INSERT INTO PEDIDO_PROVEEDOR VALUES (7002, DATE '2025-02-08', 2002);
INSERT INTO PEDIDO_PROVEEDOR VALUES (7003, DATE '2025-03-12', 2003);
INSERT INTO PEDIDO_PROVEEDOR VALUES (7004, DATE '2025-04-17', 2001);
INSERT INTO PEDIDO_PROVEEDOR VALUES (7005, DATE '2025-05-20', 2005);

INSERT INTO RECEPCION_PEDIDO VALUES (8001, 'SI', DATE '2025-01-19', 7001, 6001);
INSERT INTO RECEPCION_PEDIDO VALUES (8002, 'NO', DATE '2025-02-16', 7002, 6002);
INSERT INTO RECEPCION_PEDIDO VALUES (8003, 'SI', DATE '2025-03-21', 7003, 6003);
INSERT INTO RECEPCION_PEDIDO VALUES (8004, 'SI', DATE '2025-04-29', 7004, 6004);
INSERT INTO RECEPCION_PEDIDO VALUES (8005, 'SI', DATE '2025-05-25', 7005, 6005);

INSERT INTO ALBARAN_AUTONOMO VALUES (9001, DATE '2025-02-03', 3001);
INSERT INTO ALBARAN_AUTONOMO VALUES (9002, DATE '2025-03-04', 3002);
INSERT INTO ALBARAN_AUTONOMO VALUES (9003, DATE '2025-04-05', 3003);
INSERT INTO ALBARAN_AUTONOMO VALUES (9004, DATE '2025-05-08', 3004);
INSERT INTO ALBARAN_AUTONOMO VALUES (9005, DATE '2025-06-10', 3005);

INSERT INTO DETALLE_ALBARAN VALUES (9001, 1001, 4, 799.00);
INSERT INTO DETALLE_ALBARAN VALUES (9001, 1002, 8, 39.99);
INSERT INTO DETALLE_ALBARAN VALUES (9002, 1004, 2, 169.00);
INSERT INTO DETALLE_ALBARAN VALUES (9002, 1003, 5, 109.90);
INSERT INTO DETALLE_ALBARAN VALUES (9003, 1005, 6, 74.95);
INSERT INTO DETALLE_ALBARAN VALUES (9003, 1006, 3, 139.99);
INSERT INTO DETALLE_ALBARAN VALUES (9004, 1007, 15, 69.90);
INSERT INTO DETALLE_ALBARAN VALUES (9004, 1008, 6, 149.99);
INSERT INTO DETALLE_ALBARAN VALUES (9005, 1009, 70, 16.99);
INSERT INTO DETALLE_ALBARAN VALUES (9005, 1010, 12, 79.99);

INSERT INTO TICKET_CAJA VALUES (10001, DATE '2025-06-02', 'EFECTIVO', NULL, 5001);
INSERT INTO TICKET_CAJA VALUES (10002, DATE '2025-06-07', 'TARJETA', 'OP-607-01', 5002);
INSERT INTO TICKET_CAJA VALUES (10003, DATE '2025-06-13', 'BIZUM', 'BZ-613-02', 5003);
INSERT INTO TICKET_CAJA VALUES (10004, DATE '2025-06-19', 'TARJETA', 'OP-619-03', 5001);
INSERT INTO TICKET_CAJA VALUES (10005, DATE '2025-06-24', 'EFECTIVO', NULL, 5004);
INSERT INTO TICKET_CAJA VALUES (10006, DATE '2025-06-29', 'OTRO', 'TR-629-04', 5005);

INSERT INTO DEVOLUCION_TICKET VALUES (11001, DATE '2025-06-06', 'Teclas defectuosas', 'EFECTIVO', 1, 10002);
INSERT INTO DEVOLUCION_TICKET VALUES (11002, DATE '2025-06-14', 'Compatibilidad USB-C insuficiente', 'TARJETA', 2, 10003);
INSERT INTO DEVOLUCION_TICKET VALUES (11003, DATE '2025-06-25', 'Cambio a otro color', 'EFECTIVO', 1, 10005);

INSERT INTO DIRECCION_ENVIO VALUES (12001, 28013, 'C/ Mayor 8, 3A', 'Madrid', 'Madrid', 'SI', 4001);
INSERT INTO DIRECCION_ENVIO VALUES (12002, 28027, 'C/ Arturo Soria 90, 1C', 'Madrid', 'Madrid', 'NO', 4001);
INSERT INTO DIRECCION_ENVIO VALUES (12003,  8012, 'C/ Girona 110, 2B', 'Barcelona', 'Barcelona', 'SI', 4002);
INSERT INTO DIRECCION_ENVIO VALUES (12004, 41002, 'C/ Laraña 11, 4D', 'Sevilla', 'Sevilla', 'SI', 4003);
INSERT INTO DIRECCION_ENVIO VALUES (12005, 50008, 'C/ Asalto 30, 5A', 'Zaragoza', 'Zaragoza', 'SI', 4005);
INSERT INTO DIRECCION_ENVIO VALUES (12006, 29003, 'C/ Córdoba 20, 2B', 'Málaga', 'Málaga', 'SI', 4006);
INSERT INTO DIRECCION_ENVIO VALUES (12007, 47002, 'C/ Teresa Gil 4, 1C', 'Valladolid', 'Valladolid', 'SI', 4007);

INSERT INTO DATOS_FACTURACION VALUES (13001, 'Aragonia Dev S.L.', 'B01928374', 'Av. Cesáreo Alierta 50, Zaragoza', 4005);
INSERT INTO DATOS_FACTURACION VALUES (13002, 'Diagonal Cloud S.A.', 'A74638291', 'Av. Diagonal 520, Barcelona', 4002);
INSERT INTO DATOS_FACTURACION VALUES (13003, 'Torre del Oro Labs S.L.', 'C93827164', 'Av. República Argentina 40, Sevilla', 4003);
INSERT INTO DATOS_FACTURACION VALUES (13004, 'Gran Vía Marketing S.A.', 'D81726354', 'Gran Vía 45, Madrid', 4001);
INSERT INTO DATOS_FACTURACION VALUES (13005, 'Mediterránea Tech S.L.', 'E56473829', 'C/ Colón 25, Valencia', 4004);

INSERT INTO FACTURA_ONLINE VALUES (14001, DATE '2025-07-01', 'TARJETA',      4.99, 4001);
INSERT INTO FACTURA_ONLINE VALUES (14002, DATE '2025-07-06', 'PAYPAL',       0.00, 4002);
INSERT INTO FACTURA_ONLINE VALUES (14003, DATE '2025-07-11', 'BIZUM',        3.95, 4003);
INSERT INTO FACTURA_ONLINE VALUES (14004, DATE '2025-07-17', 'TRANSFERENCIA',6.50, 4004);
INSERT INTO FACTURA_ONLINE VALUES (14005, DATE '2025-07-23', 'TARJETA',      5.49, 4005);
INSERT INTO FACTURA_ONLINE VALUES (14006, DATE '2025-07-28', 'PAYPAL',       0.00, 4006);
INSERT INTO FACTURA_ONLINE VALUES (14007, DATE '2025-08-02', 'TARJETA',      6.49, 4007);

INSERT INTO ENVIO_ONLINE VALUES (15001, DATE '2025-07-02', 'SEG-14001-01', 'SEUR',             14001);
INSERT INTO ENVIO_ONLINE VALUES (15002, DATE '2025-07-07', 'SEG-14002-01', 'Correos Express',  14002);
INSERT INTO ENVIO_ONLINE VALUES (15003, DATE '2025-07-12', 'SEG-14003-01', 'MRW',              14003);
INSERT INTO ENVIO_ONLINE VALUES (15004, DATE '2025-07-18', 'SEG-14004-01', 'GLS',              14004);
INSERT INTO ENVIO_ONLINE VALUES (15005, DATE '2025-07-24', 'SEG-14005-01', 'SEUR',             14005);
INSERT INTO ENVIO_ONLINE VALUES (15006, DATE '2025-07-29', 'SEG-14006-01', 'DHL',              14006);
INSERT INTO ENVIO_ONLINE VALUES (15007, DATE '2025-08-03', 'SEG-14007-01', 'Correos Express',  14007);

INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16001, 1,   799.00, 14001, 1001);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16002, 2,    79.98, 14001, 1002);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16003, 1,   169.00, 14002, 1004);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16004, 2,   219.80, 14002, 1003);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16005, 1,    74.95, 14003, 1005);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16006, 1,   139.99, 14004, 1006);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16007, 3,   209.70, 14004, 1007);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16008, 1,   149.99, 14005, 1008);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16009, 5,    84.95, 14005, 1009);
INSERT INTO DETALLE_FACTURA_ONLINE VALUES (16010, 1,    79.99, 14006, 1010);

INSERT INTO DETALLE_TICKET VALUES (17001, 799.00, 1, 10001, 1001);
INSERT INTO DETALLE_TICKET VALUES (17002,  39.99, 1, 10001, 1002);
INSERT INTO DETALLE_TICKET VALUES (17003, 109.90, 1, 10002, 1003);
INSERT INTO DETALLE_TICKET VALUES (17004, 338.00, 2, 10002, 1004);
INSERT INTO DETALLE_TICKET VALUES (17005,  74.95, 1, 10003, 1005);
INSERT INTO DETALLE_TICKET VALUES (17006, 279.98, 2, 10003, 1006);
INSERT INTO DETALLE_TICKET VALUES (17007,  69.90, 1, 10004, 1007);
INSERT INTO DETALLE_TICKET VALUES (17008, 149.99, 1, 10005, 1008);
INSERT INTO DETALLE_TICKET VALUES (17009,  33.98, 2, 10005, 1009);
INSERT INTO DETALLE_TICKET VALUES (17010,  79.99, 1, 10006, 1010);

INSERT INTO DETALLE_PEDIDO_PROV VALUES (18001, 12784.00, 16, 1001, 7001);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18002,  1919.52, 48, 1002, 7001);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18003,  2477.80, 25, 1003, 7002);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18004,  3380.00, 20, 1004, 7002);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18005,  2623.25, 35, 1005, 7003);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18006,  3079.78, 22, 1006, 7003);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18007,  4194.00, 60, 1007, 7004);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18008,  2699.82, 18, 1008, 7004);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18009,  1868.90,110, 1009, 7005);
INSERT INTO DETALLE_PEDIDO_PROV VALUES (18010,  3199.60, 40, 1010, 7005);

COMMIT;

PROMPT ====== FIN DEL SCRIPT ======
